version: "3"
services:
  photogallery:
    build: .
    ports:
      - '8000:8000'
    environment:
      - secret_prod = your_djange_secret  # Generate your Djange secret key, e.g. https://djecrety.ir/ or  https://miniwebtool.com/django-secret-key-generator/